### ISSUE TITLE
Light Wallet should display valid informations for addresses without transactions.

### ISSUE THREAD

**Issue by michal-marekk** [zack-bitcoin/light-node-amoveo#3]
I loaded private key for address without any transactions, but there's still balance displayed only for previous key.

Also there're errors in browser javascript console:
```
merkle_proofs.js:31 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at link_hash (http://127.0.0.1:8080/merkle_proofs.js:31:37)
    at chain_links (http://127.0.0.1:8080/merkle_proofs.js:41:22)
    at verify_merkle (http://127.0.0.1:8080/merkle_proofs.js:85:16)
    at http://127.0.0.1:8080/merkle_proofs.js:5:16
    at http://127.0.0.1:8080/rpc.js:53:2
    at refresh_helper (http://127.0.0.1:8080/rpc.js:33:9)
    at http://127.0.0.1:8080/rpc.js:27:31
```

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/light-node-amoveo/commit/26db78e28de94dce396cbee6392d76beff14e26a
I think this update fixes the problem you are talking about.
